### ISSUE TITLE
gdk-pixbuf warning in MxImage

### ISSUE THREAD

**Issue by dlespiau** [clutter-project/mx#12]
(media-explorer:1802): GdkPixbuf-WARNING **: GdkPixbufLoader finalized without calling gdk_pixbuf_loader_close() - this is not allowed. You must explicitly end the data stream to the loader before dropping the last reference.
#0  [mex_debug_log_handler+0x4a]
#1  [g_logv+0x1df]
#2  [g_log+0x34]
#3  [gdk_pixbuf_loader_get_type+0x530]
#4  [g_object_unref+0x1c5]
#5  [mx_image_pixbuf_new+0x172]
#6  [mx_image_async_cb+0x81]
#7  [g_thread_get_initialized+0x387]
#8  [g_static_mutex_get_mutex_impl+0x135]
#9  [start_thread+0xbe]
#10  [clone+0x5e]

**Comment by thos** [comment]
Fixed in commit 9597bd0 on mx-1.4 and commit 7e236d3 on master.
