### ISSUE TITLE
Fixes for GObject introspection

### ISSUE THREAD

**Issue by nemequ** [clutter-project/mx#2]
Lots of fields are not marked as private and mx_icon_theme_get_search_paths is not documented at all.

Also, would you tweak the README file to point to the right bug tracker? I'm not sure this is it, but I don't think the ones on meego.com or clutter-project.org are right...

**Comment by nemequ** [comment]
I can't find a way to attach a patch, so: http://pastebin.com/CeiCH5x5

**Comment by ebassi** [comment]
you can fork the repository, commit the patch, and do a pull request.

**Comment by nemequ** [comment]
True, but it feels like overkill for something so trivial. I've gone ahead and done it, but is that really the preferred workflow?

**Comment by thos** [comment]
I've updated the README to point to the bugzilla at bugzilla.clutter-project.org.
