### ISSUE TITLE
mx fails to link with ld.gold linker

### ISSUE THREAD

**Issue by jlec** [clutter-project/mx#49]
CCLD   libmx-1.0.la
  GISCAN Mx-1.0.gir
./.libs/libmx-1.0.so: error: undefined reference to 'cos'
./.libs/libmx-1.0.so: error: undefined reference to 'sincos'
./.libs/libmx-1.0.so: error: undefined reference to 'sin'
./.libs/libmx-1.0.so: error: undefined reference to 'ceilf'
./.libs/libmx-1.0.so: error: undefined reference to 'rint'
./.libs/libmx-1.0.so: error: undefined reference to 'logf'
./.libs/libmx-1.0.so: error: undefined reference to 'pow'
./.libs/libmx-1.0.so: error: undefined reference to 'round'
./.libs/libmx-1.0.so: error: undefined reference to 'ceil'
./.libs/libmx-1.0.so: error: undefined reference to 'floor'
collect2: ld returned 1 exit status

Please find attached a simple patch to fix this issue

**Comment by jlec** [comment]
https://github.com/clutter-project/mx/pull/50

has the fix

**Comment by ghost** [comment]
Merged.
