### ISSUE TITLE
MxBoxLayout shouldn't manage order of child position with ClutterContainer's child list

### ISSUE THREAD

**Issue by cfsghost** [clutter-project/mx#59]
I created UI which uses MxBoxLayout widget, but I found a problem that I couldn't make one actor of MxBoxLayout to overlay onto next actor, even changing the depth of actor or raising top. :-(

I guess that MxBoxLayout is using ClutterContainer's child list to determine that order of painting and order of child position in the BoxLayout in the same time. Only if we change the order of child position to make it be last, the actor can overlay onto other actor.

My idea is, If we must use ClutterContainer's child list to manage order of painting, we shouldn't use it to determine order of widget position in BoxLayout. Maintaining own list is better.

**Comment by djdeath** [comment]
MxBoxLayout always worked that way. This is a 2D widget container, and it's not supposed to allocate children in a such a way that they would overlap.

If you want a container that paints children according to the z-order I'm afraid you have no other solution than writing your own container.

**Comment by cfsghost** [comment]
I think Mx is a 2.5D+ GUI Toolkit, why don't just provide an easy way to set z-index that's just like css/html stuffs?

**Comment by magcius** [comment]
How are you using MxBoxLayout in a way where the actors overlap?

Also, yes, paint order is locked to insertion order. That's how Clutter works.

**Comment by cfsghost** [comment]
I want to implement an effect that increasing depth of actor when it is focused(looks like making it bigger). But it will be covered by next actor of BoxLayout.

Another idea is, I want to make a behavior that scale this actor to make it fullscreen with animation when user selected. But if it cannot be set z-order/z-index, I am not gonna be able to do it because actor is to be covered by other actors when scaling. :-(
