### ISSUE TITLE
viewport: implement apply_transform and get_paint_volume 

### ISSUE THREAD

**Issue by mmdemo** [clutter-project/mx#68]
Could u please explain me why are these two functions are replaced for paint and pick virtual functions.

I am having a problem without these two functions!!

Conatiner (contains)->scrollView(contains)->viewPort(contains)->Mycontainer

If i give conatiner size as 200 / 200, then paint and pick is not working as expected. it is even painted even beyond 200pixel height

**Comment by djdeath** [comment]
I see that the last patch on MxViewport removes the "clip-to-allocation" property's default value.
I think that might explain your painting problem.

Can you try to call clutter_actor_set_clip_to_allocation(viewPort, TRUE);  ?
It should fix the painting problem.
Meanwhile I'm gonna check why we changed this.

**Comment by tomeuv** [comment]
This may be relevant as well: https://bugzilla.gnome.org/show_bug.cgi?id=686225

**Comment by mmdemo** [comment]
why is that "clip-to allocation" property has been removed ?

**Comment by mmdemo** [comment]
Ok that is fixing my problem
Is that is a bug?
:)

**Comment by djdeath** [comment]
Yes, it is. But it's actually a KineticScrollView bug.
We changed the policy to get the clip done by the scrollview rather that the Viewport.
I'm fixing that right now.

**Comment by mmdemo** [comment]
?? How can i get the latest version?

**Comment by djdeath** [comment]
Should be fixed in 5287920fa13daaa85df379671c572bca2a930b8c
