### ISSUE TITLE
viewPort: 

### ISSUE THREAD

**Issue by mmdemo** [clutter-project/mx#69]
ScrollView(contains/Mxbin)->Viewport(contains/Mxbin)->Mycontainer(scrollable)
while scrolling Mycontainer scrolls but all childrens are not visible.
Why it is happening so?

**Comment by djdeath** [comment]
You don't  need a Viewport if MyContainer already implements MxScrollable.

**Comment by mmdemo** [comment]
but i need animation(elastic effect) for the Mycontainer... as if the view port is upon that. how can i achieve that?

**Comment by djdeath** [comment]
Get the adjustment for MyContainer and deactivate clamping on value.

**Comment by mmdemo** [comment]
Yes thank u :)
