### ISSUE TITLE
MxAdjustment

### ISSUE THREAD

**Issue by mmdemo** [clutter-project/mx#70]
ScrollView(contains)->Mycontainer(scrollable)
Adjustment for Mycontainer is setting elastic property!, when i scroll with the elastic effect it will settle at the top most of container. How can i make it to settle to the middle.?

**Comment by tomeuv** [comment]
You can see how MxKineticScrollView does it for its ::clamp-to-center property.

**Comment by mmdemo** [comment]
if i give ::clamp-to-center property to true for scrollview it is no effect

**Comment by djdeath** [comment]
Could you try reverting that commit c6335e469534496bd44194fc7e7118a5827c3e8a and see if that fix the problem?

**Comment by mmdemo** [comment]
I am using 1.4.6.. those lines of code is not available

what is the behaviour of clamp to center could u please tell me

**Comment by mmdemo** [comment]
According to me clamp to center should make may container place in the centre of the container

**Comment by djdeath** [comment]
clamp-to-center is a different property use to stop the animations in the middle of the step increment for the MxAdjustment.
I don't think the feature you would like has ever been implemented.

**Comment by djdeath** [comment]
I'm not sure what you would like exactly.
Discussing with other people, I'm being told that what you might want could be some padding at the top of you Scrollable.

**Comment by mmdemo** [comment]
Ok thank u.

**Comment by mmdemo** [comment]
Description:

Container->scrollView->MyContainer
whenever there is a finger scroll on Mycontainer, it will start scrolling ,clamping should occur on the mid of the Container.

Lets say, Conatainer size is 400 pixel and  Mycontainer is 200 pixel, when i scroll and leave, Mycontainer should settle at 200 pixel of the Conatainer.

**Comment by mmdemo** [comment]
anybody ans me?/

**Comment by djdeath** [comment]
I'm sorry I really don't understand what it is you would like.

Besides, a 400px container having a child of 200px +  200px padding is supposed to be fully visible, therefore no need for scrolling.

**Comment by Cwiiis** [comment]
Is there actually a bug here? If there isn't, it would be better to use IRC, mailing lists or e-mail to have this conversation. For the sanity of those who are receiving e-mail notifications :)

**Comment by djdeath** [comment]
Yeah let's do that : irc.gnome.org channel : #clutter
