### ISSUE TITLE
GISCAN fails due "mx_texture_frame_get_type"

### ISSUE THREAD

**Issue by infapi00** [clutter-project/mx#77]
I get this error compiling recent mx:
  GISCAN Mx-2.0.gir
mx-clipboard.h:25: Warning: Mx: multiple comment blocks documenting 'SECTION:mx-clipboard:' identifier.
mx-settings.h:79: Warning: Mx: multiple comment blocks documenting 'mx_settings_get_default:' identifier.
mx-types.h:21: Warning: Mx: multiple comment blocks documenting 'SECTION:mx-types:' identifier.
mx-types.h:21: Warning: Mx: multiple comment blocks documenting 'SECTION:mx-types:' identifier.
mx-types.h:21: Warning: Mx: multiple comment blocks documenting 'SECTION:mx-types:' identifier.
mx-types.h:21: Warning: Mx: multiple comment blocks documenting 'SECTION:mx-types:' identifier.
mx-version.h:28: Warning: Mx: multiple comment blocks documenting 'SECTION:mx-version:' identifier.
/home/devel/GNOME3/source/mx/mx/tmp-introspectLnYh29/Mx-2.0.o:(.data+0x240): undefined reference to `mx_texture_frame_get_type'

On the last commit (e5f2db840473d92b1e592443109bf0c6bb945d17) it is said that "This patch also removes the MxTextureFrame actor" so I assume that there was an error removing it.

**Comment by infapi00** [comment]
FWIW, removing the line "GType mx_texture_frame_get_type (void) G_GNUC_CONST;" from mx-texture-frame.h solved this problem to me.

**Comment by thos** [comment]
Fixed in commit a8b7689
